version: '3.4'
services:
  dev-env:
    volumes:
      # Mount the root folder that contains .git
      - ..:/workspace
      # [Optional] For reusing Git SSH keys.
      # - ~/.ssh:/root/.ssh-local:ro
      - "/var/run/docker.sock:/var/run/docker.sock"
    build:
      context: ..
      target: DEV
      dockerfile: Dockerfile
      args:
        # Run as "privileged" so we can access the Docker Host from inside the container
        privileged: "true"
    env_file:
      - ../.env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # command: /bin/sh -c "while sleep 1000; do :; done"

